# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
#都可以得到相同的結果

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [2]:
# 記得先 Import 正確的套件
import numpy as np


In [3]:
A = np.random.random((5, 5))

_A = np.max(A) - np.min(A)
print((A - np.min(A)) / _A)

[[0.29062627 0.94524737 0.65611027 0.93827357 0.30924694]
 [0.83942043 0.85855498 0.76199887 0.05374904 0.4302912 ]
 [0.99505298 0.08816899 1.         0.32207255 0.56998117]
 [0.49546447 0.         0.78035619 0.68146752 0.70842615]
 [0.31486191 0.20008084 0.24670024 0.81392899 0.63964656]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [4]:
B = np.random.randint(1,100,10)
maxB = B.max
B[np.argmax(B)] = -1

print(B)

[32 82 59 90 -1 62 79 36 36  8]
