# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


#list()只會把第一層的元素轉換成 List，多層的話只有第一層會轉；

print('list(a): ', list(a))

#tolist()才能達成多層的型態轉換。

print('tolist(): ', a.tolist())


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [2]:
# 記得先 Import 正確的套件

import numpy as np


In [7]:
a = np.random.randint(10, size=6) 
print(a)
print('陣列維度:',a.ndim)
print('每個維度的大小',a.shape)
print('陣列元素一共有',a.size)
print('陣列中的資料型態',a.dtype)
print('陣列中每個元素佔用的空間',a.itemsize)
print('陣列長度',len(a))
print('陣列的資料型態',type(a))

[9 4 7 1 8 1]
陣列維度: 1
每個維度的大小 (6,)
陣列元素一共有 6
陣列中的資料型態 int32
陣列中每個元素佔用的空間 4
陣列長度 6
陣列的資料型態 <class 'numpy.ndarray'>


In [8]:
b = np.random.randint(10, size=(3,4)) 
print(b)
print('陣列維度:',b.ndim)
print('每個維度的大小',b.shape)
print('陣列元素一共有',b.size)
print('陣列中的資料型態',b.dtype)
print('陣列中每個元素佔用的空間',b.itemsize)
print('陣列長度',len(b))
print('陣列的資料型態',type(b))

[[8 6 2 4]
 [6 6 5 8]
 [7 7 1 7]]
陣列維度: 2
每個維度的大小 (3, 4)
陣列元素一共有 12
陣列中的資料型態 int32
陣列中每個元素佔用的空間 4
陣列長度 3
陣列的資料型態 <class 'numpy.ndarray'>


In [9]:
c = np.random.randint(10, size=(2,3,2))
print(c)
print('陣列維度:',c.ndim)
print('每個維度的大小',c.shape)
print('陣列元素一共有',c.size)
print('陣列中的資料型態',c.dtype)
print('陣列中每個元素佔用的空間',c.itemsize)
print('陣列長度',len(c))
print('陣列的資料型態',type(c))

[[[5 2]
  [3 1]
  [5 8]]

 [[9 4]
  [2 8]
  [9 4]]]
陣列維度: 3
每個維度的大小 (2, 3, 2)
陣列元素一共有 12
陣列中的資料型態 int32
陣列中每個元素佔用的空間 4
陣列長度 2
陣列的資料型態 <class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 6, 7, 3, 7, 5]
[7, 6, 7, 3, 7, 5]


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[array([5, 7, 4, 6]), array([9, 4, 0, 1]), array([9, 1, 2, 9])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [10]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[9, 4, 7, 1, 8, 1]
[[8, 6, 2, 4], [6, 6, 5, 8], [7, 7, 1, 7]]
[[[5, 2], [3, 1], [5, 8]], [[9, 4], [2, 8], [9, 4]]]


[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
